### PR TITLE
Add new functions build_content_type() and build_content_disposition()

### LINKED ISSUE #2: Build method for content type
Hello,

When this module had construction method for Content-Type which takes result of `parse_content_type()` as the argument, I thought that it was convenient. 

Like so (Since it wrote promptly, there may be a point that something is not good);
https://gist.github.com/moznion/7496660

Since this processing can be written easily, a user may actually be what to write individually. However, I thought that the way which offered unific processing was good because it doesn't make trifling difference (e.g. treatment of white space, etc...) will not be induced.

### PR DESCRIPTION
**Pull request by pali**
These functions compose Content-Type and Content-Disposition headers.

Non-ASCII attributes are encoded to UTF-8 and too long (> 78 bytes)
attributes are split, both according to RFC 2231.

For compatibility reasons, ASCII version of too long or non-ASCII attribute
is also present, but is truncated and encoded to ASCII via Text::Unidecode
module.

Fixes #2

### CODE REVIEW

**Comment by dxdc** [comment]
@rjbs ... any chance these could be reviewed and/or merged into a new release? :) let me know if I can help.

**Comment by pali** [comment]
@rjbs ping, can you review these changes?

**Comment by pali** [comment]
@rjbs: Are there any issues in this PR? If not could it be merged? Because more people are waiting for this new functionality.

**Comment by rjbs** [comment]
Thanks, applied.  I will add a commit to normalize the indenting to match existing code.

**Pull request merged**
